export interface Area {
  slug: string;
  name: string;
}

export interface City {
  slug: string;
  name: string;
  state?: string;
  areas: Area[];
}

export const cities: City[] = [
  {
    slug: "agra",
    name: "Agra",
    state: "Uttar Pradesh",
    areas: [
      { slug: "taj-ganj", name: "Taj Ganj" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "shahganj", name: "Shahganj" },
      { slug: "fatehabad-road", name: "Fatehabad Road" },
      { slug: "kamla-nagar", name: "Kamla Nagar" },
      { slug: "sikandra", name: "Sikandra" },
      { slug: "mg-road", name: "MG Road" },
      { slug: "sanjay-place", name: "Sanjay Place" },
      { slug: "dayalbagh", name: "Dayalbagh" },
      { slug: "mathura-road", name: "Mathura Road" },
    ],
  },
  {
    slug: "ahmedabad",
    name: "Ahmedabad",
    state: "Gujarat",
    areas: [
      { slug: "navrangpura", name: "Navrangpura" },
      { slug: "cg-road", name: "CG Road" },
      { slug: "prahlad-nagar", name: "Prahlad Nagar" },
      { slug: "satellite", name: "Satellite" },
      { slug: "bopal", name: "Bopal" },
      { slug: "maninagar", name: "Maninagar" },
      { slug: "vastrapur", name: "Vastrapur" },
      { slug: "thaltej", name: "Thaltej" },
      { slug: "motera", name: "Motera" },
      { slug: "naroda", name: "Naroda" },
      { slug: "bapunagar", name: "Bapunagar" },
    ],
  },
  {
    slug: "ajmer",
    name: "Ajmer",
    state: "Rajasthan",
    areas: [
      { slug: "nasirabad", name: "Nasirabad" },
      { slug: "vaishali-nagar", name: "Vaishali Nagar" },
      { slug: "beawar-road", name: "Beawar Road" },
      { slug: "pushkar-road", name: "Pushkar Road" },
      { slug: "kishangarh", name: "Kishangarh" },
      { slug: "anna-sagar", name: "Anna Sagar" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "dargah-bazar", name: "Dargah Bazar" },
    ],
  },
  {
    slug: "aligarh",
    name: "Aligarh",
    state: "Uttar Pradesh",
    areas: [
      { slug: "center-point", name: "Center Point" },
      { slug: "ramghat-road", name: "Ramghat Road" },
      { slug: "marris-road", name: "Marris Road" },
      { slug: "shamshad-market", name: "Shamshad Market" },
      { slug: "dhanipur", name: "Dhanipur" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "amu-campus", name: "AMU Campus" },
    ],
  },
  {
    slug: "allahabad",
    name: "Allahabad",
    state: "Uttar Pradesh",
    areas: [
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "george-town", name: "George Town" },
      { slug: "naini", name: "Naini" },
      { slug: "jhusi", name: "Jhusi" },
      { slug: "phaphamau", name: "Phaphamau" },
      { slug: "kareli", name: "Kareli" },
      { slug: "kydganj", name: "Kydganj" },
      { slug: "colonelganj", name: "Colonelganj" },
      { slug: "lucknow-road", name: "Lucknow Road" },
    ],
  },
  {
    slug: "alwar",
    name: "Alwar",
    state: "Rajasthan",
    areas: [
      { slug: "hope-circle", name: "Hope Circle" },
      { slug: "manu-marg", name: "Manu Marg" },
      { slug: "bhiwadi", name: "Bhiwadi" },
      { slug: "tijara", name: "Tijara" },
      { slug: "malakhera", name: "Malakhera" },
      { slug: "ramgarh", name: "Ramgarh" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "amritsar",
    name: "Amritsar",
    state: "Punjab",
    areas: [
      { slug: "hall-bazar", name: "Hall Bazar" },
      { slug: "golden-temple-road", name: "Golden Temple Road" },
      { slug: "airport-road", name: "Airport Road" },
      { slug: "majitha-road", name: "Majitha Road" },
      { slug: "sultanwind", name: "Sultanwind" },
      { slug: "mcleod-road", name: "McLeod Road" },
      { slug: "ranjit-avenue", name: "Ranjit Avenue" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "aurangabad",
    name: "Aurangabad",
    state: "Maharashtra",
    areas: [
      { slug: "cidco", name: "CIDCO" },
      { slug: "chikalthana", name: "Chikalthana" },
      { slug: "jalna-road", name: "Jalna Road" },
      { slug: "garkheda", name: "Garkheda" },
      { slug: "mukundwadi", name: "Mukundwadi" },
      { slug: "satara", name: "Satara" },
      { slug: "samernath", name: "Samernath" },
      { slug: "tv-center", name: "TV Center" },
    ],
  },
  {
    slug: "ayodhya",
    name: "Ayodhya",
    state: "Uttar Pradesh",
    areas: [
      { slug: "naya-ghat", name: "Naya Ghat" },
      { slug: "sahadatganj", name: "Sahadatganj" },
      { slug: "bikapur", name: "Bikapur" },
      { slug: "tanda", name: "Tanda" },
      { slug: "darshan-nagar", name: "Darshan Nagar" },
      { slug: "faizabad", name: "Faizabad" },
      { slug: "sugriv-kila", name: "Sugriv Kila" },
    ],
  },
  {
    slug: "bangalore",
    name: "Bangalore",
    state: "Karnataka",
    areas: [
      { slug: "koramangala", name: "Koramangala" },
      { slug: "indiranagar", name: "Indiranagar" },
      { slug: "whitefield", name: "Whitefield" },
      { slug: "electronic-city", name: "Electronic City" },
      { slug: "hsr-layout", name: "HSR Layout" },
      { slug: "btm-layout", name: "BTM Layout" },
      { slug: "jayanagar", name: "Jayanagar" },
      { slug: "marathahalli", name: "Marathahalli" },
      { slug: "sarjapur-road", name: "Sarjapur Road" },
      { slug: "hebbal", name: "Hebbal" },
      { slug: "yelahanka", name: "Yelahanka" },
      { slug: "mg-road", name: "MG Road" },
    ],
  },
  {
    slug: "bareilly",
    name: "Bareilly",
    state: "Uttar Pradesh",
    areas: [
      { slug: "cantonment", name: "Cantonment" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "subhash-nagar", name: "Subhash Nagar" },
      { slug: "rajendra-nagar", name: "Rajendra Nagar" },
      { slug: "nawabganj", name: "Nawabganj" },
      { slug: "faridpur", name: "Faridpur" },
      { slug: "baheri", name: "Baheri" },
      { slug: "izzatnagar", name: "Izzatnagar" },
    ],
  },
  {
    slug: "bhopal",
    name: "Bhopal",
    state: "Madhya Pradesh",
    areas: [
      { slug: "mp-nagar", name: "MP Nagar" },
      { slug: "habibganj", name: "Habibganj" },
      { slug: "ayodhya-nagar", name: "Ayodhya Nagar" },
      { slug: "govindpura", name: "Govindpura" },
      { slug: "bairagarh", name: "Bairagarh" },
      { slug: "tulsi-nagar", name: "Tulsi Nagar" },
      { slug: "arera-colony", name: "Arera Colony" },
      { slug: "ttt-nagar", name: "TT Nagar" },
      { slug: "kolar-road", name: "Kolar Road" },
    ],
  },
  {
    slug: "bikaner",
    name: "Bikaner",
    state: "Rajasthan",
    areas: [
      { slug: "vinayak", name: "Vinayak" },
      { slug: "manda", name: "Manda" },
      { slug: "rani-bazar", name: "Rani Bazar" },
      { slug: "gajner", name: "Gajner" },
      { slug: "pugal-road", name: "Pugal Road" },
      { slug: "ridhi-sidhi", name: "Ridhi Sidhi" },
      { slug: "barmer-road", name: "Barmer Road" },
    ],
  },
  {
    slug: "bilaspur",
    name: "Bilaspur",
    state: "Chhattisgarh",
    areas: [
      { slug: "vyapar-vihar", name: "Vyapar Vihar" },
      { slug: "sadar-bazar", name: "Sadar Bazar" },
      { slug: "link-road", name: "Link Road" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "sarkanda", name: "Sarkanda" },
      { slug: "tifra", name: "Tifra" },
      { slug: "konari", name: "Konari" },
    ],
  },
  {
    slug: "bokaro",
    name: "Bokaro",
    state: "Jharkhand",
    areas: [
      { slug: "city-center", name: "City Center" },
      { slug: "sector-4", name: "Sector 4" },
      { slug: "chas", name: "Chas" },
      { slug: "ramkanali", name: "Ramkanali" },
      { slug: "sector-9", name: "Sector 9" },
      { slug: "berma", name: "Berma" },
      { slug: "phusro", name: "Phusro" },
    ],
  },
  {
    slug: "chandigarh",
    name: "Chandigarh",
    state: "Punjab",
    areas: [
      { slug: "sector-17", name: "Sector 17" },
      { slug: "sector-22", name: "Sector 22" },
      { slug: "sector-35", name: "Sector 35" },
      { slug: "sector-43", name: "Sector 43" },
      { slug: "mani-majra", name: "Mani Majra" },
      { slug: "panchkula", name: "Panchkula" },
      { slug: "mohali", name: "Mohali" },
      { slug: "zirakpur", name: "Zirakpur" },
    ],
  },
  {
    slug: "chennai",
    name: "Chennai",
    state: "Tamil Nadu",
    areas: [
      { slug: "t-nagar", name: "T Nagar" },
      { slug: "anna-nagar", name: "Anna Nagar" },
      { slug: "velachery", name: "Velachery" },
      { slug: "adyar", name: "Adyar" },
      { slug: "nungambakkam", name: "Nungambakkam" },
      { slug: "mylapore", name: "Mylapore" },
      { slug: "perambur", name: "Perambur" },
      { slug: "egmore", name: "Egmore" },
      { slug: "tambaram", name: "Tambaram" },
      { slug: "guindy", name: "Guindy" },
      { slug: "porur", name: "Porur" },
      { slug: "omr", name: "OMR" },
    ],
  },
  {
    slug: "chittorgarh",
    name: "Chittorgarh",
    state: "Rajasthan",
    areas: [
      { slug: "fort-area", name: "Fort Area" },
      { slug: "pratapgarh", name: "Pratapgarh" },
      { slug: "bundi-road", name: "Bundi Road" },
      { slug: "gangrar", name: "Gangrar" },
      { slug: "nimbahera", name: "Nimbahera" },
      { slug: "rawatbhata", name: "Rawatbhata" },
    ],
  },
  {
    slug: "coimbatore",
    name: "Coimbatore",
    state: "Tamil Nadu",
    areas: [
      { slug: "rs-puram", name: "RS Puram" },
      { slug: "gandhipuram", name: "Gandhipuram" },
      { slug: "peelamedu", name: "Peelamedu" },
      { slug: "hope-college", name: "Hope College" },
      { slug: "singanallur", name: "Singanallur" },
      { slug: "saibaba-colony", name: "Saibaba Colony" },
      { slug: "tidel-park", name: "Tidel Park" },
      { slug: "selvapuram", name: "Selvapuram" },
    ],
  },
  {
    slug: "cuttack",
    name: "Cuttack",
    state: "Odisha",
    areas: [
      { slug: "cantonment-road", name: "Cantonment Road" },
      { slug: "buxi-bazar", name: "Buxi Bazar" },
      { slug: "madhupatna", name: "Madhupatna" },
      { slug: "chauliaganj", name: "Chauliaganj" },
      { slug: "jagatpur", name: "Jagatpur" },
      { slug: "mangalabag", name: "Mangalabag" },
      { slug: "bidanasi", name: "Bidanasi" },
    ],
  },
  {
    slug: "daman",
    name: "Daman",
    state: "D&D",
    areas: [
      { slug: "moti-daman", name: "Moti Daman" },
      { slug: "nani-daman", name: "Nani Daman" },
      { slug: "kadaiya", name: "Kadaiya" },
      { slug: "marwad", name: "Marwad" },
      { slug: "diu", name: "Diu" },
      { slug: "somnath-road", name: "Somnath Road" },
    ],
  },
  {
    slug: "darbhanga",
    name: "Darbhanga",
    state: "Bihar",
    areas: [
      { slug: "laheriasarai", name: "Laheriasarai" },
      { slug: "minapur", name: "Minapur" },
      { slug: "benta", name: "Benta" },
      { slug: "bahadurpur", name: "Bahadurpur" },
      { slug: "kamtaul", name: "Kamtaul" },
      { slug: "jale-road", name: "Jale Road" },
    ],
  },
  {
    slug: "dehradun",
    name: "Dehradun",
    state: "Uttarakhand",
    areas: [
      { slug: "rajpur-road", name: "Rajpur Road" },
      { slug: "paltan-bazar", name: "Paltan Bazar" },
      { slug: "clock-tower", name: "Clock Tower" },
      { slug: "prem-nagar", name: "Prem Nagar" },
      { slug: "clement-town", name: "Clement Town" },
      { slug: "saharanpur-road", name: "Saharanpur Road" },
      { slug: "mussoorie-road", name: "Mussoorie Road" },
      { slug: "race-course", name: "Race Course" },
    ],
  },
  {
    slug: "delhi",
    name: "Delhi",
    state: "Delhi",
    areas: [
      { slug: "connaught-place", name: "Connaught Place" },
      { slug: "karol-bagh", name: "Karol Bagh" },
      { slug: "dwarka", name: "Dwarka" },
      { slug: "rohini", name: "Rohini" },
      { slug: "janakpuri", name: "Janakpuri" },
      { slug: "lajpat-nagar", name: "Lajpat Nagar" },
      { slug: "saket", name: "Saket" },
      { slug: "aerocity", name: "Aerocity" },
      { slug: "paharganj", name: "Paharganj" },
      { slug: "nehru-place", name: "Nehru Place" },
      { slug: "vasant-kunj", name: "Vasant Kunj" },
      { slug: "green-park", name: "Green Park" },
      { slug: "hauz-khas", name: "Hauz Khas" },
      { slug: "pitampura", name: "Pitampura" },
      { slug: "mayur-vihar", name: "Mayur Vihar" },
    ],
  },
  {
    slug: "dhanbad",
    name: "Dhanbad",
    state: "Jharkhand",
    areas: [
      { slug: "jharia", name: "Jharia" },
      { slug: "katras", name: "Katras" },
      { slug: "sindri", name: "Sindri" },
      { slug: "govindpur", name: "Govindpur" },
      { slug: "rajganj", name: "Rajganj" },
      { slug: "saraiya", name: "Saraiya" },
      { slug: "bank-more", name: "Bank More" },
    ],
  },
  {
    slug: "digha",
    name: "Digha",
    state: "West Bengal",
    areas: [
      { slug: "mandarmani", name: "Mandarmani" },
      { slug: "shankarpur", name: "Shankarpur" },
      { slug: "east-digha", name: "East Digha" },
      { slug: "west-digha", name: "West Digha" },
      { slug: "junput", name: "Junput" },
      { slug: "contai", name: "Contai" },
    ],
  },
  {
    slug: "durgapur",
    name: "Durgapur",
    state: "West Bengal",
    areas: [
      { slug: "bidhannagar", name: "Bidhannagar" },
      { slug: "city-center", name: "City Center" },
      { slug: "nachan-road", name: "Nachan Road" },
      { slug: "benachity", name: "Benachity" },
      { slug: "bhirnapur", name: "Bhirnapur" },
      { slug: "andal", name: "Andal" },
      { slug: "asansol", name: "Asansol" },
    ],
  },
  {
    slug: "faridabad",
    name: "Faridabad",
    state: "Haryana",
    areas: [
      { slug: "nhpc-chowk", name: "NHPC Chowk" },
      { slug: "old-faridabad", name: "Old Faridabad" },
      { slug: "sector-16", name: "Sector 16" },
      { slug: "sector-21", name: "Sector 21" },
      { slug: "sector-28", name: "Sector 28" },
      { slug: "sector-37", name: "Sector 37" },
      { slug: "ballabgarh", name: "Ballabgarh" },
      { slug: "neharpar", name: "Neharpar" },
    ],
  },
  {
    slug: "gandhinagar",
    name: "Gandhinagar",
    state: "Gujarat",
    areas: [
      { slug: "sector-5", name: "Sector 5" },
      { slug: "sector-11", name: "Sector 11" },
      { slug: "sector-15", name: "Sector 15" },
      { slug: "sector-21", name: "Sector 21" },
      { slug: "sector-25", name: "Sector 25" },
      { slug: "infocity", name: "Infocity" },
      { slug: "adalaj", name: "Adalaj" },
    ],
  },
  {
    slug: "gaya",
    name: "Gaya",
    state: "Bihar",
    areas: [
      { slug: "manpur", name: "Manpur" },
      { slug: "bodh-gaya", name: "Bodh Gaya" },
      { slug: "tekari", name: "Tekari" },
      { slug: "dobhi", name: "Dobhi" },
      { slug: "amas", name: "Amas" },
      { slug: "bankebazar", name: "Bankebazar" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "ghaziabad",
    name: "Ghaziabad",
    state: "Uttar Pradesh",
    areas: [
      { slug: "vaishali", name: "Vaishali" },
      { slug: "indirapuram", name: "Indirapuram" },
      { slug: "kaushambi", name: "Kaushambi" },
      { slug: "raj-nagar", name: "Raj Nagar" },
      { slug: "loni", name: "Loni" },
      { slug: "modinagar", name: "Modinagar" },
      { slug: "sahibabad", name: "Sahibabad" },
      { slug: "hapur-road", name: "Hapur Road" },
    ],
  },
  {
    slug: "goa",
    name: "Goa",
    state: "Goa",
    areas: [
      { slug: "panaji", name: "Panaji" },
      { slug: "calangute", name: "Calangute" },
      { slug: "mapusa", name: "Mapusa" },
      { slug: "margao", name: "Margao" },
      { slug: "vasco-da-gama", name: "Vasco da Gama" },
      { slug: "ponda", name: "Ponda" },
      { slug: "anjuna", name: "Anjuna" },
      { slug: "baga", name: "Baga" },
      { slug: "vagator", name: "Vagator" },
    ],
  },
  {
    slug: "gorakhpur",
    name: "Gorakhpur",
    state: "Uttar Pradesh",
    areas: [
      { slug: "gorakhnath", name: "Gorakhnath" },
      { slug: "basantpur", name: "Basantpur" },
      { slug: "arogyanagar", name: "Arogyanagar" },
      { slug: "rustampur", name: "Rustampur" },
      { slug: "padri-bazar", name: "Padri Bazar" },
      { slug: "medical-college-road", name: "Medical College Road" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "greater-noida",
    name: "Greater Noida",
    state: "Uttar Pradesh",
    areas: [
      { slug: "alpha-2", name: "Alpha 2" },
      { slug: "beta-2", name: "Beta 2" },
      { slug: "gamma-1", name: "Gamma 1" },
      { slug: "delta-1", name: "Delta 1" },
      { slug: "zeta-1", name: "Zeta 1" },
      { slug: "omega-1", name: "Omega 1" },
      { slug: "knowledge-park", name: "Knowledge Park" },
      { slug: "sector-36", name: "Sector 36" },
    ],
  },
  {
    slug: "gurdaspur",
    name: "Gurdaspur",
    state: "Punjab",
    areas: [
      { slug: "batala", name: "Batala" },
      { slug: "dhariwal", name: "Dhariwal" },
      { slug: "dina-nagar", name: "Dina Nagar" },
      { slug: "fatehgarh-churian", name: "Fatehgarh Churian" },
      { slug: "kalanaur", name: "Kalanaur" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "gurgaon",
    name: "Gurgaon",
    state: "Haryana",
    areas: [
      { slug: "cyber-city", name: "Cyber City" },
      { slug: "sohna-road", name: "Sohna Road" },
      { slug: "sector-57", name: "Sector 57" },
      { slug: "sector-49", name: "Sector 49" },
      { slug: "golf-course-road", name: "Golf Course Road" },
      { slug: "palam-vihar", name: "Palam Vihar" },
      { slug: "sushant-lok", name: "Sushant Lok" },
      { slug: "dlf-phase-1", name: "DLF Phase 1" },
      { slug: "mg-road", name: "MG Road" },
    ],
  },
  {
    slug: "guwahati",
    name: "Guwahati",
    state: "Assam",
    areas: [
      { slug: "gandhi-basti", name: "Gandhi Basti" },
      { slug: "bhangagarh", name: "Bhangagarh" },
      { slug: "zoo-road", name: "Zoo Road" },
      { slug: "christianbasti", name: "Christianbasti" },
      { slug: "beltola", name: "Beltola" },
      { slug: "narengi", name: "Narengi" },
      { slug: "rukminigaon", name: "Rukminigaon" },
      { slug: "hatigaon", name: "Hatigaon" },
    ],
  },
  {
    slug: "gwalior",
    name: "Gwalior",
    state: "Madhya Pradesh",
    areas: [
      { slug: "lashkar", name: "Lashkar" },
      { slug: "morar", name: "Morar" },
      { slug: "gwalior-fort", name: "Gwalior Fort" },
      { slug: "city-center", name: "City Center" },
      { slug: "deen-dayal-nagar", name: "Deen Dayal Nagar" },
      { slug: "thatipur", name: "Thatipur" },
      { slug: "bank-colony", name: "Bank Colony" },
    ],
  },
  {
    slug: "hardoi",
    name: "Hardoi",
    state: "Uttar Pradesh",
    areas: [
      { slug: "madauli", name: "Madauli" },
      { slug: "bharawan", name: "Bharawan" },
      { slug: "pali", name: "Pali" },
      { slug: "shahabad", name: "Shahabad" },
      { slug: "sandila", name: "Sandila" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "haridwar",
    name: "Haridwar",
    state: "Uttarakhand",
    areas: [
      { slug: "har-ki-pauri", name: "Har Ki Pauri" },
      { slug: "jwalapur", name: "Jwalapur" },
      { slug: "shivalik-nagar", name: "Shivalik Nagar" },
      { slug: "sidcul", name: "SIDCUL" },
      { slug: "ranipur", name: "Ranipur" },
      { slug: "rishikesh-road", name: "Rishikesh Road" },
      { slug: "bhel-road", name: "BHEL Road" },
    ],
  },
  {
    slug: "hazaribagh",
    name: "Hazaribagh",
    state: "Jharkhand",
    areas: [
      { slug: "kokar", name: "Kokar" },
      { slug: "lalpur", name: "Lalpur" },
      { slug: "upper-bazar", name: "Upper Bazar" },
      { slug: "sadar", name: "Sadar" },
      { slug: "khelgaon", name: "Khelgaon" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "hisar",
    name: "Hisar",
    state: "Haryana",
    areas: [
      { slug: "model-town", name: "Model Town" },
      { slug: "urban-estate", name: "Urban Estate" },
      { slug: "red-square-market", name: "Red Square Market" },
      { slug: "barsi-gate", name: "Barsi Gate" },
      { slug: "railway-road", name: "Railway Road" },
      { slug: "aggarwal-colony", name: "Aggarwal Colony" },
    ],
  },
  {
    slug: "howrah",
    name: "Howrah",
    state: "West Bengal",
    areas: [
      { slug: "liluah", name: "Liluah" },
      { slug: "santragachi", name: "Santragachi" },
      { slug: "shibpur", name: "Shibpur" },
      { slug: "bally", name: "Bally" },
      { slug: "bantra", name: "Bantra" },
      { slug: "dasnagar", name: "Dasnagar" },
      { slug: "andul", name: "Andul" },
    ],
  },
  {
    slug: "hubli-dharwad",
    name: "Hubli Dharwad",
    state: "Karnataka",
    areas: [
      { slug: "keshwapur", name: "Keshwapur" },
      { slug: "gokul-road", name: "Gokul Road" },
      { slug: "deshpande-nagar", name: "Deshpande Nagar" },
      { slug: "navanagar", name: "Navanagar" },
      { slug: "vidyanagar", name: "Vidyanagar" },
      { slug: "unkal", name: "Unkal" },
    ],
  },
  {
    slug: "hyderabad",
    name: "Hyderabad",
    state: "Telangana",
    areas: [
      { slug: "banjara-hills", name: "Banjara Hills" },
      { slug: "jubilee-hills", name: "Jubilee Hills" },
      { slug: "gachibowli", name: "Gachibowli" },
      { slug: "hitech-city", name: "Hitech City" },
      { slug: "secunderabad", name: "Secunderabad" },
      { slug: "kukatpally", name: "Kukatpally" },
      { slug: "kondapur", name: "Kondapur" },
      { slug: "madhapur", name: "Madhapur" },
      { slug: "begumpet", name: "Begumpet" },
      { slug: "somajiguda", name: "Somajiguda" },
      { slug: "ameerpet", name: "Ameerpet" },
      { slug: "sr-nagar", name: "SR Nagar" },
      { slug: "dilsukhnagar", name: "Dilsukhnagar" },
      { slug: "lb-nagar", name: "LB Nagar" },
      { slug: "uppal", name: "Uppal" },
    ],
  },
  {
    slug: "indore",
    name: "Indore",
    state: "Madhya Pradesh",
    areas: [
      { slug: "vijay-nagar", name: "Vijay Nagar" },
      { slug: "palasia", name: "Palasia" },
      { slug: "sapna-sangeeta", name: "Sapna Sangeeta" },
      { slug: "rau", name: "Rau" },
      { slug: "bhawarkuan", name: "Bhawarkuan" },
      { slug: "sudama-nagar", name: "Sudama Nagar" },
      { slug: "niranjanpur", name: "Niranjanpur" },
      { slug: "malharganj", name: "Malharganj" },
      { slug: "lasudia", name: "Lasudia" },
    ],
  },
  {
    slug: "jabalpur",
    name: "Jabalpur",
    state: "Madhya Pradesh",
    areas: [
      { slug: "napier-town", name: "Napier Town" },
      { slug: "gwarighat", name: "Gwarighat" },
      { slug: "madan-mahal", name: "Madan Mahal" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "gohalpur", name: "Gohalpur" },
      { slug: "damoh-nagar", name: "Damoh Nagar" },
      { slug: "kundam", name: "Kundam" },
    ],
  },
  {
    slug: "jagdalpur",
    name: "Jagdalpur",
    state: "Chhattisgarh",
    areas: [
      { slug: "chitrakoot", name: "Chitrakoot" },
      { slug: "tamorpingla", name: "Tamorpingla" },
      { slug: "dantewada", name: "Dantewada" },
      { slug: "bhopalpatnam", name: "Bhopalpatnam" },
      { slug: "bijapur", name: "Bijapur" },
    ],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    areas: [
      { slug: "malviya-nagar", name: "Malviya Nagar" },
      { slug: "vaishali-nagar", name: "Vaishali Nagar" },
      { slug: "mansarovar", name: "Mansarovar" },
      { slug: "c-scheme", name: "C-Scheme" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "bani-park", name: "Bani Park" },
      { slug: "tonk-road", name: "Tonk Road" },
      { slug: "jagatpura", name: "Jagatpura" },
      { slug: "sanganer", name: "Sanganer" },
      { slug: "sodala", name: "Sodala" },
      { slug: "pratap-nagar", name: "Pratap Nagar" },
      { slug: "ajmer-road", name: "Ajmer Road" },
    ],
  },
  {
    slug: "jamshedpur",
    name: "Jamshedpur",
    state: "Jharkhand",
    areas: [
      { slug: "bistupur", name: "Bistupur" },
      { slug: "sakchi", name: "Sakchi" },
      { slug: "jugsalai", name: "Jugsalai" },
      { slug: "adityapur", name: "Adityapur" },
      { slug: "mango", name: "Mango" },
      { slug: "pardih", name: "Pardih" },
      { slug: "telco", name: "Telco" },
      { slug: "sonari", name: "Sonari" },
    ],
  },
  {
    slug: "jhansi",
    name: "Jhansi",
    state: "Uttar Pradesh",
    areas: [
      { slug: "sipri-bazar", name: "Sipri Bazar" },
      { slug: "cantonment", name: "Cantonment" },
      { slug: "naya-bazar", name: "Naya Bazar" },
      { slug: "gopal-mandir", name: "Gopal Mandir" },
      { slug: "raksa", name: "Raksa" },
      { slug: "gwalior-road", name: "Gwalior Road" },
      { slug: "bajrang-bazar", name: "Bajrang Bazar" },
    ],
  },
  {
    slug: "jodhpur",
    name: "Jodhpur",
    state: "Rajasthan",
    areas: [
      { slug: "paota", name: "Paota" },
      { slug: "shastri-nagar", name: "Shastri Nagar" },
      { slug: "ratanada", name: "Ratanada" },
      { slug: "mandore", name: "Mandore" },
      { slug: "pal-road", name: "Pal Road" },
      { slug: "umaid-bhawan", name: "Umaid Bhawan" },
      { slug: "sojati-gate", name: "Sojati Gate" },
      { slug: "circuit-house", name: "Circuit House" },
    ],
  },
  {
    slug: "kalyan-dombivli",
    name: "Kalyan Dombivli",
    state: "Maharashtra",
    areas: [
      { slug: "kalyan-east", name: "Kalyan East" },
      { slug: "kalyan-west", name: "Kalyan West" },
      { slug: "dombivli-east", name: "Dombivli East" },
      { slug: "dombivli-west", name: "Dombivli West" },
      { slug: "ulhasnagar", name: "Ulhasnagar" },
      { slug: "ambernath", name: "Ambernath" },
      { slug: "badlapur", name: "Badlapur" },
    ],
  },
  {
    slug: "kanpur",
    name: "Kanpur",
    state: "Uttar Pradesh",
    areas: [
      { slug: "swaroop-nagar", name: "Swaroop Nagar" },
      { slug: "govind-nagar", name: "Govind Nagar" },
      { slug: "kidwai-nagar", name: "Kidwai Nagar" },
      { slug: "vikas-nagar", name: "Vikas Nagar" },
      { slug: "anwarganj", name: "Anwarganj" },
      { slug: "nawabganj", name: "Nawabganj" },
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "kakadeo", name: "Kakadeo" },
    ],
  },
  {
    slug: "kanyakumari",
    name: "Kanyakumari",
    state: "Tamil Nadu",
    areas: [
      { slug: "suchindram", name: "Suchindram" },
      { slug: "nagercoil", name: "Nagercoil" },
      { slug: "colachel", name: "Colachel" },
      { slug: "marthandam", name: "Marthandam" },
      { slug: "padmanabhapuram", name: "Padmanabhapuram" },
      { slug: "thiruvithamcode", name: "Thiruvithamcode" },
    ],
  },
  {
    slug: "kedarnath",
    name: "Kedarnath",
    state: "Uttarakhand",
    areas: [
      { slug: "ukhimath", name: "Ukhimath" },
      { slug: "sonprayag", name: "Sonprayag" },
      { slug: "gaurikund", name: "Gaurikund" },
      { slug: "guptakashi", name: "Guptakashi" },
      { slug: "rudraprayag", name: "Rudraprayag" },
    ],
  },
  {
    slug: "kochi",
    name: "Kochi",
    state: "Kerala",
    areas: [
      { slug: "ernakulam", name: "Ernakulam" },
      { slug: "fort-kochi", name: "Fort Kochi" },
      { slug: "vyttila", name: "Vyttila" },
      { slug: "kalamassery", name: "Kalamassery" },
      { slug: "tripunithura", name: "Tripunithura" },
      { slug: "edapally", name: "Edapally" },
      { slug: "aluva", name: "Aluva" },
      { slug: "thevara", name: "Thevara" },
    ],
  },
  {
    slug: "kolkata",
    name: "Kolkata",
    state: "West Bengal",
    areas: [
      { slug: "park-street", name: "Park Street" },
      { slug: "salt-lake", name: "Salt Lake" },
      { slug: "new-town", name: "New Town" },
      { slug: "ballygunge", name: "Ballygunge" },
      { slug: "alipore", name: "Alipore" },
      { slug: "esplanade", name: "Esplanade" },
      { slug: "jadavpur", name: "Jadavpur" },
      { slug: "tollygunge", name: "Tollygunge" },
      { slug: "dum-dum", name: "Dum Dum" },
      { slug: "ultadanga", name: "Ultadanga" },
      { slug: "behala", name: "Behala" },
    ],
  },
  {
    slug: "kota",
    name: "Kota",
    state: "Rajasthan",
    areas: [
      { slug: "mahaveer-nagar", name: "Mahaveer Nagar" },
      { slug: "vigyan-nagar", name: "Vigyan Nagar" },
      { slug: "talwandi", name: "Talwandi" },
      { slug: "rangbari", name: "Rangbari" },
      { slug: "aerodrome", name: "Aerodrome" },
      { slug: "dada-bari", name: "Dada Bari" },
      { slug: "jawahar-nagar", name: "Jawahar Nagar" },
    ],
  },
  {
    slug: "kushinagar",
    name: "Kushinagar",
    state: "Uttar Pradesh",
    areas: [
      { slug: "padrauna", name: "Padrauna" },
      { slug: "kasia", name: "Kasia" },
      { slug: "tamkuhi", name: "Tamkuhi" },
      { slug: "hata", name: "Hata" },
      { slug: "ramkola", name: "Ramkola" },
      { slug: "bansgaon", name: "Bansgaon" },
    ],
  },
  {
    slug: "lucknow",
    name: "Lucknow",
    state: "Uttar Pradesh",
    areas: [
      { slug: "gomti-nagar", name: "Gomti Nagar" },
      { slug: "hazratganj", name: "Hazratganj" },
      { slug: "indira-nagar", name: "Indira Nagar" },
      { slug: "charbagh", name: "Charbagh" },
      { slug: "alambagh", name: "Alambagh" },
      { slug: "aliganj", name: "Aliganj" },
      { slug: "vibhuti-khand", name: "Vibhuti Khand" },
      { slug: "rajajipuram", name: "Rajajipuram" },
      { slug: "jankipuram", name: "Jankipuram" },
      { slug: "lalbagh", name: "Lalbagh" },
      { slug: "chinhat", name: "Chinhat" },
      { slug: "faizabad-road", name: "Faizabad Road" },
    ],
  },
  {
    slug: "ludhiana",
    name: "Ludhiana",
    state: "Punjab",
    areas: [
      { slug: "model-town", name: "Model Town" },
      { slug: "brs-nagar", name: "BRS Nagar" },
      { slug: "sarabha-nagar", name: "Sarabha Nagar" },
      { slug: "haibowal", name: "Haibowal" },
      { slug: "gurdev-nagar", name: "Gurdev Nagar" },
      { slug: "pakhowal-road", name: "Pakhowal Road" },
      { slug: "field-ganj", name: "Field Ganj" },
    ],
  },
  {
    slug: "madurai",
    name: "Madurai",
    state: "Tamil Nadu",
    areas: [
      { slug: "anna-nagar", name: "Anna Nagar" },
      { slug: "ss-colony", name: "SS Colony" },
      { slug: "k-k-nagar", name: "KK Nagar" },
      { slug: "pasumalai", name: "Pasumalai" },
      { slug: "tallakulam", name: "Tallakulam" },
      { slug: "simmakkal", name: "Simmakkal" },
      { slug: "avaniyapuram", name: "Avaniyapuram" },
    ],
  },
  {
    slug: "manali",
    name: "Manali",
    state: "Himachal Pradesh",
    areas: [
      { slug: "old-manali", name: "Old Manali" },
      { slug: "vashisht", name: "Vashisht" },
      { slug: "hadimba-devi", name: "Hadimba Devi" },
      { slug: "kullu", name: "Kullu" },
      { slug: "bhuntar", name: "Bhuntar" },
      { slug: "naggar", name: "Naggar" },
    ],
  },
  {
    slug: "mathura",
    name: "Mathura",
    state: "Uttar Pradesh",
    areas: [
      { slug: "vrindavan-road", name: "Vrindavan Road" },
      { slug: "bhuteshwar", name: "Bhuteshwar" },
      { slug: "govardhan", name: "Govardhan" },
      { slug: "masani", name: "Masani" },
      { slug: "krishna-nagar", name: "Krishna Nagar" },
      { slug: "vikram-vihar", name: "Vikram Vihar" },
    ],
  },
  {
    slug: "meerut",
    name: "Meerut",
    state: "Uttar Pradesh",
    areas: [
      { slug: "ganga-nagar", name: "Ganga Nagar" },
      { slug: "shastri-nagar", name: "Shastri Nagar" },
      { slug: "garh-road", name: "Garh Road" },
      { slug: "hapur-road", name: "Hapur Road" },
      { slug: "modipuram", name: "Modipuram" },
      { slug: "abu-nala", name: "Abu Nala" },
      { slug: "civil-lines", name: "Civil Lines" },
    ],
  },
  {
    slug: "moradabad",
    name: "Moradabad",
    state: "Uttar Pradesh",
    areas: [
      { slug: "civil-lines", name: "Civil Lines" },
      { slug: "kutchery", name: "Kutchery" },
      { slug: "factory-area", name: "Factory Area" },
      { slug: "rampur-road", name: "Rampur Road" },
      { slug: "dehradun-road", name: "Dehradun Road" },
      { slug: "bazar-samiti", name: "Bazar Samiti" },
    ],
  },
  {
    slug: "mumbai",
    name: "Mumbai",
    state: "Maharashtra",
    areas: [
      { slug: "andheri", name: "Andheri" },
      { slug: "bandra", name: "Bandra" },
      { slug: "juhu", name: "Juhu" },
      { slug: "powai", name: "Powai" },
      { slug: "borivali", name: "Borivali" },
      { slug: "dadar", name: "Dadar" },
      { slug: "worli", name: "Worli" },
      { slug: "colaba", name: "Colaba" },
      { slug: "goregaon", name: "Goregaon" },
      { slug: "kurla", name: "Kurla" },
      { slug: "malad", name: "Malad" },
      { slug: "vile-parle", name: "Vile Parle" },
      { slug: "marine-lines", name: "Marine Lines" },
      { slug: "versova", name: "Versova" },
      { slug: "santacruz", name: "Santacruz" },
    ],
  },
  {
    slug: "mussoorie",
    name: "Mussoorie",
    state: "Uttarakhand",
    areas: [
      { slug: "library-chowk", name: "Library Chowk" },
      { slug: "landour", name: "Landour" },
      { slug: "cloud-end", name: "Cloud End" },
      { slug: "happy-valley", name: "Happy Valley" },
      { slug: "camelback-road", name: "Camelback Road" },
      { slug: "barlowganj", name: "Barlowganj" },
    ],
  },
  {
    slug: "muzaffarpur",
    name: "Muzaffarpur",
    state: "Bihar",
    areas: [
      { slug: "motijheel", name: "Motijheel" },
      { slug: "mithanpura", name: "Mithanpura" },
      { slug: "juran-chapra", name: "Juran Chapra" },
      { slug: "sadae-road", name: "Sadae Road" },
      { slug: "ramna", name: "Ramna" },
      { slug: "bela-road", name: "Bela Road" },
    ],
  },
  {
    slug: "mysore",
    name: "Mysore",
    state: "Karnataka",
    areas: [
      { slug: "nazarbad", name: "Nazarbad" },
      { slug: "sayyaji-rao-road", name: "Sayyaji Rao Road" },
      { slug: "jayalakshmipuram", name: "Jayalakshmipuram" },
      { slug: "kuvempunagar", name: "Kuvempunagar" },
      { slug: "rajivnagar", name: "Rajivnagar" },
      { slug: "brindavan", name: "Brindavan" },
      { slug: "yelwala", name: "Yelwala" },
    ],
  },
  {
    slug: "nagpur",
    name: "Nagpur",
    state: "Maharashtra",
    areas: [
      { slug: "dharampeth", name: "Dharampeth" },
      { slug: "ramdaspeth", name: "Ramdaspeth" },
      { slug: "sitabuldi", name: "Sitabuldi" },
      { slug: "mankapur", name: "Mankapur" },
      { slug: "wardhaman-nagar", name: "Wardhaman Nagar" },
      { slug: "itwari", name: "Itwari" },
      { slug: "hingna", name: "Hingna" },
      { slug: "ambazari", name: "Ambazari" },
    ],
  },
  {
    slug: "nashik",
    name: "Nashik",
    state: "Maharashtra",
    areas: [
      { slug: "college-road", name: "College Road" },
      { slug: "gangapur-road", name: "Gangapur Road" },
      { slug: "cidco", name: "CIDCO" },
      { slug: "satpur", name: "Satpur" },
      { slug: "panchavati", name: "Panchavati" },
      { slug: "chandwad", name: "Chandwad" },
      { slug: "igatpuri", name: "Igatpuri" },
      { slug: "sinnar", name: "Sinnar" },
    ],
  },
  {
    slug: "navi-mumbai",
    name: "Navi Mumbai",
    state: "Maharashtra",
    areas: [
      { slug: "vashi", name: "Vashi" },
      { slug: "belapur", name: "Belapur" },
      { slug: "kharghar", name: "Kharghar" },
      { slug: "airoli", name: "Airoli" },
      { slug: "kopar-khairane", name: "Kopar Khairane" },
      { slug: "ghansoli", name: "Ghansoli" },
      { slug: "nerul", name: "Nerul" },
      { slug: "panvel", name: "Panvel" },
    ],
  },
  {
    slug: "noida",
    name: "Noida",
    state: "Uttar Pradesh",
    areas: [
      { slug: "sector-18", name: "Sector 18" },
      { slug: "sector-62", name: "Sector 62" },
      { slug: "sector-63", name: "Sector 63" },
      { slug: "sector-76", name: "Sector 76" },
      { slug: "sector-137", name: "Sector 137" },
      { slug: "greater-noida-west", name: "Greater Noida West" },
      { slug: "filmcity", name: "Filmcity" },
      { slug: "expressway", name: "Expressway" },
    ],
  },
  {
    slug: "pali",
    name: "Pali",
    state: "Rajasthan",
    areas: [
      { slug: "sumerpur", name: "Sumerpur" },
      { slug: "bali", name: "Bali" },
      { slug: "sojat", name: "Sojat" },
      { slug: "marwar-junction", name: "Marwar Junction" },
      { slug: "raipur", name: "Raipur" },
      { slug: "takhatgarh", name: "Takhatgarh" },
    ],
  },
  {
    slug: "panipat",
    name: "Panipat",
    state: "Haryana",
    areas: [
      { slug: "sector-12", name: "Sector 12" },
      { slug: "sector-18", name: "Sector 18" },
      { slug: "model-town", name: "Model Town" },
      { slug: "brahmpuri", name: "Brahmpuri" },
      { slug: "chandni-bagh", name: "Chandni Bagh" },
      { slug: "samalkha", name: "Samalkha" },
    ],
  },
  {
    slug: "patna",
    name: "Patna",
    state: "Bihar",
    areas: [
      { slug: "patliputra", name: "Patliputra" },
      { slug: "boring-road", name: "Boring Road" },
      { slug: "rajendra-nagar", name: "Rajendra Nagar" },
      { slug: "kankarbagh", name: "Kankarbagh" },
      { slug: "fraser-road", name: "Fraser Road" },
      { slug: "bailey-road", name: "Bailey Road" },
      { slug: "danapur", name: "Danapur" },
      { slug: "boring-canal-road", name: "Boring Canal Road" },
      { slug: "ashiana-nagar", name: "Ashiana Nagar" },
      { slug: "saguna-more", name: "Saguna More" },
      { slug: "gandhi-maidan", name: "Gandhi Maidan" },
      { slug: "anisabad", name: "Anisabad" },
    ],
  },
  {
    slug: "pune",
    name: "Pune",
    state: "Maharashtra",
    areas: [
      { slug: "kothrud", name: "Kothrud" },
      { slug: "hinjewadi", name: "Hinjewadi" },
      { slug: "viman-nagar", name: "Viman Nagar" },
      { slug: "wakad", name: "Wakad" },
      { slug: "baner", name: "Baner" },
      { slug: "aundh", name: "Aundh" },
      { slug: "hadapsar", name: "Hadapsar" },
      { slug: "koregaon-park", name: "Koregaon Park" },
      { slug: "camp", name: "Camp" },
      { slug: "magarpatta", name: "Magarpatta" },
      { slug: "kharadi", name: "Kharadi" },
      { slug: "shivajinagar", name: "Shivajinagar" },
    ],
  },
  {
    slug: "puri",
    name: "Puri",
    state: "Odisha",
    areas: [
      { slug: "sea-beach", name: "Sea Beach" },
      { slug: "bali-sahi", name: "Bali Sahi" },
      { slug: "mochi-sahi", name: "Mochi Sahi" },
      { slug: "chakratirtha", name: "Chakratirtha" },
      { slug: "marine-drive", name: "Marine Drive" },
      { slug: "swargadwar", name: "Swargadwar" },
      { slug: "gaudabazar", name: "Gaudabazar" },
    ],
  },
  {
    slug: "raipur",
    name: "Raipur",
    state: "Chhattisgarh",
    areas: [
      { slug: "amanaka", name: "Amanaka" },
      { slug: "tikrapara", name: "Tikrapara" },
      { slug: "moudhapara", name: "Moudhapara" },
      { slug: "ring-road-1", name: "Ring Road 1" },
      { slug: "ring-road-2", name: "Ring Road 2" },
      { slug: "pandri", name: "Pandri" },
      { slug: "avanti-vihar", name: "Avanti Vihar" },
      { slug: "devendra-nagar", name: "Devendra Nagar" },
    ],
  },
  {
    slug: "rajkot",
    name: "Rajkot",
    state: "Gujarat",
    areas: [
      { slug: "kalavad-road", name: "Kalavad Road" },
      { slug: "mavdi", name: "Mavdi" },
      { slug: "gondal-road", name: "Gondal Road" },
      { slug: "150-feet-ring-road", name: "150 Feet Ring Road" },
      { slug: "aji-dam-road", name: "Aji Dam Road" },
      { slug: "metoda", name: "Metoda" },
      { slug: "university-road", name: "University Road" },
    ],
  },
  {
    slug: "ramgarh",
    name: "Ramgarh",
    state: "Jharkhand",
    areas: [
      { slug: "churchu", name: "Churchu" },
      { slug: "mandu", name: "Mandu" },
      { slug: "chitarpur", name: "Chitarpur" },
      { slug: "marar", name: "Marar" },
      { slug: "badkagaon", name: "Badkagaon" },
      { slug: "patratu", name: "Patratu" },
    ],
  },
  {
    slug: "ranchi",
    name: "Ranchi",
    state: "Jharkhand",
    areas: [
      { slug: "lalpur", name: "Lalpur" },
      { slug: "ashok-nagar", name: "Ashok Nagar" },
      { slug: "kanke-road", name: "Kanke Road" },
      { slug: "doranda", name: "Doranda" },
      { slug: "harmu", name: "Harmu" },
      { slug: "bariatu", name: "Bariatu" },
      { slug: "namkum", name: "Namkum" },
      { slug: "sukhdeonagar", name: "Sukhdeonagar" },
    ],
  },
  {
    slug: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    areas: [
      { slug: "tapovan", name: "Tapovan" },
      { slug: "lakshman-jhula", name: "Lakshman Jhula" },
      { slug: "swarg-ashram", name: "Swarg Ashram" },
      { slug: "muni-ki-reti", name: "Muni Ki Reti" },
      { slug: "haridwar-road", name: "Haridwar Road" },
      { slug: "badrinath-road", name: "Badrinath Road" },
    ],
  },
  {
    slug: "sikar",
    name: "Sikar",
    state: "Rajasthan",
    areas: [
      { slug: "bajaj-gram", name: "Bajaj Gram" },
      { slug: "neem-ka-thana", name: "Neem Ka Thana" },
      { slug: "laxmangarh", name: "Laxmangarh" },
      { slug: "fatehpur", name: "Fatehpur" },
      { slug: "shrimadhopur", name: "Shrimadhopur" },
    ],
  },
  {
    slug: "solapur",
    name: "Solapur",
    state: "Maharashtra",
    areas: [
      { slug: "bsd-colony", name: "BSD Colony" },
      { slug: "vir-nagar", name: "Vir Nagar" },
      { slug: "latur-road", name: "Latur Road" },
      { slug: "akkalkot", name: "Akkalkot" },
      { slug: "pandharpur", name: "Pandharpur" },
      { slug: "market-yard", name: "Market Yard" },
    ],
  },
  {
    slug: "sonipat",
    name: "Sonipat",
    state: "Haryana",
    areas: [
      { slug: "murthal", name: "Murthal" },
      { slug: "kundli", name: "Kundli" },
      { slug: "rai", name: "Rai" },
      { slug: "ganaur", name: "Ganaur" },
      { slug: "atlas-road", name: "Atlas Road" },
      { slug: "sector-16", name: "Sector 16" },
    ],
  },
  {
    slug: "srinagar",
    name: "Srinagar",
    state: "J&K",
    areas: [
      { slug: "dal-lake", name: "Dal Lake" },
      { slug: "lal-chowk", name: "Lal Chowk" },
      { slug: "rajbagh", name: "Rajbagh" },
      { slug: "hazratbal", name: "Hazratbal" },
      { slug: "hyderpora", name: "Hyderpora" },
      { slug: "panthachowk", name: "Panthachowk" },
      { slug: "zainakote", name: "Zainakote" },
    ],
  },
  {
    slug: "surat",
    name: "Surat",
    state: "Gujarat",
    areas: [
      { slug: "adajan", name: "Adajan" },
      { slug: "ghod-dod", name: "Ghod Dod" },
      { slug: "vesu", name: "Vesu" },
      { slug: "katargam", name: "Katargam" },
      { slug: "rander", name: "Rander" },
      { slug: "althan", name: "Althan" },
      { slug: "udhna", name: "Udhna" },
      { slug: "sachin", name: "Sachin" },
      { slug: "pandesara", name: "Pandesara" },
    ],
  },
  {
    slug: "thane",
    name: "Thane",
    state: "Maharashtra",
    areas: [
      { slug: "kasarvadavali", name: "Kasarvadavali" },
      { slug: "kopri", name: "Kopri" },
      { slug: "teen-haath-naka", name: "Teen Haath Naka" },
      { slug: "wagle-estate", name: "Wagle Estate" },
      { slug: "manpada", name: "Manpada" },
      { slug: "majiwada", name: "Majiwada" },
      { slug: "hiranandani-estate", name: "Hiranandani Estate" },
    ],
  },
  {
    slug: "tirupati",
    name: "Tirupati",
    state: "Andhra Pradesh",
    areas: [
      { slug: "tirumala", name: "Tirumala" },
      { slug: "alipiri", name: "Alipiri" },
      { slug: "renigunta", name: "Renigunta" },
      { slug: "chandragiri", name: "Chandragiri" },
      { slug: "pakala", name: "Pakala" },
      { slug: "srikalahasti", name: "Srikalahasti" },
      { slug: "yerpedu", name: "Yerpedu" },
    ],
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    areas: [
      { slug: "fatehsagar", name: "Fatehsagar" },
      { slug: "surajpol", name: "Surajpol" },
      { slug: "chetak", name: "Chetak" },
      { slug: "hiran-magri", name: "Hiran Magri" },
      { slug: "pratap-nagar", name: "Pratap Nagar" },
      { slug: "bhuwana", name: "Bhuwana" },
      { slug: "ambamata", name: "Ambamata" },
    ],
  },
  {
    slug: "ujjain",
    name: "Ujjain",
    state: "Madhya Pradesh",
    areas: [
      { slug: "mahakaleshwar", name: "Mahakaleshwar" },
      { slug: "freeganj", name: "Freeganj" },
      { slug: "dewas-road", name: "Dewas Road" },
      { slug: "nai-sadak", name: "Nai Sadak" },
      { slug: "nanakheda-nagar", name: "Nanakheda Nagar" },
      { slug: "tower-chowk", name: "Tower Chowk" },
      { slug: "makshi-road", name: "Makshi Road" },
    ],
  },
  {
    slug: "vadodara",
    name: "Vadodara",
    state: "Gujarat",
    areas: [
      { slug: "alkapuri", name: "Alkapuri" },
      { slug: "akota", name: "Akota" },
      { slug: "ellora-park", name: "Ellora Park" },
      { slug: "vasna", name: "Vasna" },
      { slug: "gotri", name: "Gotri" },
      { slug: "manjalpur", name: "Manjalpur" },
      { slug: "harinagar", name: "Harinagar" },
    ],
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    areas: [
      { slug: "assi-ghat", name: "Assi Ghat" },
      { slug: "dashashwamedh-ghat", name: "Dashashwamedh Ghat" },
      { slug: "sigra", name: "Sigra" },
      { slug: "lanka", name: "Lanka" },
      { slug: "cantonment", name: "Cantonment" },
      { slug: "shivpur", name: "Shivpur" },
      { slug: "pandeypur", name: "Pandeypur" },
      { slug: "sunderpur", name: "Sunderpur" },
    ],
  },
  {
    slug: "vijayawada",
    name: "Vijayawada",
    state: "Andhra Pradesh",
    areas: [
      { slug: "benz-circle", name: "Benz Circle" },
      { slug: "patamata", name: "Patamata" },
      { slug: "labbipeta", name: "Labbipeta" },
      { slug: "suryaraopet", name: "Suryaraopet" },
      { slug: "gunadala", name: "Gunadala" },
      { slug: "krishnalanka", name: "Krishnalanka" },
      { slug: "autonagar", name: "Autonagar" },
    ],
  },
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    state: "Andhra Pradesh",
    areas: [
      { slug: "mvp-colony", name: "MVP Colony" },
      { slug: "siripuram", name: "Siripuram" },
      { slug: "rushikonda", name: "Rushikonda" },
      { slug: "dwaraka-nagar", name: "Dwaraka Nagar" },
      { slug: "gajuwaka", name: "Gajuwaka" },
      { slug: "mphb-colony", name: "MPHB Colony" },
      { slug: "bheemunipatnam", name: "Bheemunipatnam" },
    ],
  },
  {
    slug: "wayanad",
    name: "Wayanad",
    state: "Kerala",
    areas: [
      { slug: "kalpetta", name: "Kalpetta" },
      { slug: "sulthan-bathery", name: "Sulthan Bathery" },
      { slug: "mananthavady", name: "Mananthavady" },
      { slug: "ambalavayal", name: "Ambalavayal" },
      { slug: "vythiri", name: "Vythiri" },
      { slug: "panamaram", name: "Panamaram" },
    ],
  },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}

export function getAreaBySlug(citySlug: string, areaSlug: string): Area | undefined {
  const city = getCityBySlug(citySlug);
  return city?.areas.find((a) => a.slug === areaSlug);
}

