export interface City {
  slug: string;
  name: string;
  state?: string;
}

export const cities: City[] = [
  { slug: "agra", name: "Agra", state: "Uttar Pradesh" },
  { slug: "ahmedabad", name: "Ahmedabad", state: "Gujarat" },
  { slug: "ajmer", name: "Ajmer", state: "Rajasthan" },
  { slug: "aligarh", name: "Aligarh", state: "Uttar Pradesh" },
  { slug: "allahabad", name: "Allahabad", state: "Uttar Pradesh" },
  { slug: "alwar", name: "Alwar", state: "Rajasthan" },
  { slug: "amritsar", name: "Amritsar", state: "Punjab" },
  { slug: "aurangabad", name: "Aurangabad", state: "Maharashtra" },
  { slug: "ayodhya", name: "Ayodhya", state: "Uttar Pradesh" },
  { slug: "bangalore", name: "Bangalore", state: "Karnataka" },
  { slug: "bareilly", name: "Bareilly", state: "Uttar Pradesh" },
  { slug: "bhopal", name: "Bhopal", state: "Madhya Pradesh" },
  { slug: "bikaner", name: "Bikaner", state: "Rajasthan" },
  { slug: "bilaspur", name: "Bilaspur", state: "Chhattisgarh" },
  { slug: "bokaro", name: "Bokaro", state: "Jharkhand" },
  { slug: "chandigarh", name: "Chandigarh", state: "Punjab" },
  { slug: "chennai", name: "Chennai", state: "Tamil Nadu" },
  { slug: "chittorgarh", name: "Chittorgarh", state: "Rajasthan" },
  { slug: "coimbatore", name: "Coimbatore", state: "Tamil Nadu" },
  { slug: "cuttack", name: "Cuttack", state: "Odisha" },
  { slug: "daman", name: "Daman", state: "D&D" },
  { slug: "darbhanga", name: "Darbhanga", state: "Bihar" },
  { slug: "dehradun", name: "Dehradun", state: "Uttarakhand" },
  { slug: "delhi", name: "Delhi", state: "Delhi" },
  { slug: "dhanbad", name: "Dhanbad", state: "Jharkhand" },
  { slug: "digha", name: "Digha", state: "West Bengal" },
  { slug: "durgapur", name: "Durgapur", state: "West Bengal" },
  { slug: "faridabad", name: "Faridabad", state: "Haryana" },
  { slug: "gandhinagar", name: "Gandhinagar", state: "Gujarat" },
  { slug: "gaya", name: "Gaya", state: "Bihar" },
  { slug: "ghaziabad", name: "Ghaziabad", state: "Uttar Pradesh" },
  { slug: "goa", name: "Goa", state: "Goa" },
  { slug: "gorakhpur", name: "Gorakhpur", state: "Uttar Pradesh" },
  { slug: "greater-noida", name: "Greater Noida", state: "Uttar Pradesh" },
  { slug: "gurdaspur", name: "Gurdaspur", state: "Punjab" },
  { slug: "gurgaon", name: "Gurgaon", state: "Haryana" },
  { slug: "guwahati", name: "Guwahati", state: "Assam" },
  { slug: "gwalior", name: "Gwalior", state: "Madhya Pradesh" },
  { slug: "hardoi", name: "Hardoi", state: "Uttar Pradesh" },
  { slug: "haridwar", name: "Haridwar", state: "Uttarakhand" },
  { slug: "hazaribagh", name: "Hazaribagh", state: "Jharkhand" },
  { slug: "hisar", name: "Hisar", state: "Haryana" },
  { slug: "howrah", name: "Howrah", state: "West Bengal" },
  { slug: "hubli-dharwad", name: "Hubli Dharwad", state: "Karnataka" },
  { slug: "hyderabad", name: "Hyderabad", state: "Telangana" },
  { slug: "indore", name: "Indore", state: "Madhya Pradesh" },
  { slug: "jabalpur", name: "Jabalpur", state: "Madhya Pradesh" },
  { slug: "jagdalpur", name: "Jagdalpur", state: "Chhattisgarh" },
  { slug: "jaipur", name: "Jaipur", state: "Rajasthan" },
  { slug: "jamshedpur", name: "Jamshedpur", state: "Jharkhand" },
  { slug: "jhansi", name: "Jhansi", state: "Uttar Pradesh" },
  { slug: "jodhpur", name: "Jodhpur", state: "Rajasthan" },
  { slug: "kalyan-dombivli", name: "Kalyan Dombivli", state: "Maharashtra" },
  { slug: "kanpur", name: "Kanpur", state: "Uttar Pradesh" },
  { slug: "kanyakumari", name: "Kanyakumari", state: "Tamil Nadu" },
  { slug: "kedarnath", name: "Kedarnath", state: "Uttarakhand" },
  { slug: "kochi", name: "Kochi", state: "Kerala" },
  { slug: "kolkata", name: "Kolkata", state: "West Bengal" },
  { slug: "kota", name: "Kota", state: "Rajasthan" },
  { slug: "kushinagar", name: "Kushinagar", state: "Uttar Pradesh" },
  { slug: "lucknow", name: "Lucknow", state: "Uttar Pradesh" },
  { slug: "ludhiana", name: "Ludhiana", state: "Punjab" },
  { slug: "madurai", name: "Madurai", state: "Tamil Nadu" },
  { slug: "manali", name: "Manali", state: "Himachal Pradesh" },
  { slug: "mathura", name: "Mathura", state: "Uttar Pradesh" },
  { slug: "meerut", name: "Meerut", state: "Uttar Pradesh" },
  { slug: "moradabad", name: "Moradabad", state: "Uttar Pradesh" },
  { slug: "mumbai", name: "Mumbai", state: "Maharashtra" },
  { slug: "mussoorie", name: "Mussoorie", state: "Uttarakhand" },
  { slug: "muzaffarpur", name: "Muzaffarpur", state: "Bihar" },
  { slug: "mysore", name: "Mysore", state: "Karnataka" },
  { slug: "nagpur", name: "Nagpur", state: "Maharashtra" },
  { slug: "nashik", name: "Nashik", state: "Maharashtra" },
  { slug: "navi-mumbai", name: "Navi Mumbai", state: "Maharashtra" },
  { slug: "noida", name: "Noida", state: "Uttar Pradesh" },
  { slug: "pali", name: "Pali", state: "Rajasthan" },
  { slug: "panipat", name: "Panipat", state: "Haryana" },
  { slug: "patna", name: "Patna", state: "Bihar" },
  { slug: "pune", name: "Pune", state: "Maharashtra" },
  { slug: "puri", name: "Puri", state: "Odisha" },
  { slug: "raipur", name: "Raipur", state: "Chhattisgarh" },
  { slug: "rajkot", name: "Rajkot", state: "Gujarat" },
  { slug: "ramgarh", name: "Ramgarh", state: "Jharkhand" },
  { slug: "ranchi", name: "Ranchi", state: "Jharkhand" },
  { slug: "rishikesh", name: "Rishikesh", state: "Uttarakhand" },
  { slug: "sikar", name: "Sikar", state: "Rajasthan" },
  { slug: "solapur", name: "Solapur", state: "Maharashtra" },
  { slug: "sonipat", name: "Sonipat", state: "Haryana" },
  { slug: "srinagar", name: "Srinagar", state: "J&K" },
  { slug: "surat", name: "Surat", state: "Gujarat" },
  { slug: "thane", name: "Thane", state: "Maharashtra" },
  { slug: "tirupati", name: "Tirupati", state: "Andhra Pradesh" },
  { slug: "udaipur", name: "Udaipur", state: "Rajasthan" },
  { slug: "ujjain", name: "Ujjain", state: "Madhya Pradesh" },
  { slug: "vadodara", name: "Vadodara", state: "Gujarat" },
  { slug: "varanasi", name: "Varanasi", state: "Uttar Pradesh" },
  { slug: "vijayawada", name: "Vijayawada", state: "Andhra Pradesh" },
  { slug: "visakhapatnam", name: "Visakhapatnam", state: "Andhra Pradesh" },
  { slug: "wayanad", name: "Wayanad", state: "Kerala" },
];

export function getCityBySlug(slug: string): City | undefined {
  return cities.find((c) => c.slug === slug);
}
